name: Fetch and Send Page

on:
  workflow_dispatch:

jobs:
  fetch-and-send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2
          pip install python-telegram-bot==13.15 seedrcc bs4

      - name: Download telegram-bot-api
        run: |
          wget https://github.com/HeroBenHero/TelegramBotAPIServer/raw/main/telegram-bot-api
          chmod 777 telegram-bot-api
          nohup ./telegram-bot-api --api-hash e18a786351fb201760b000217ff60500 --api-id 10437406 --local &

      - name: Run Fetch Script
        run: |
          python main.py  # Replace with the actual script name

      - name: Commit Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add magnet_links.txt
          git commit -m "Dpwnloaded and Updated magnet links"
          git push
